#!/usr/bin/env bash
# This script is displaying numbers from 1 to 100, with Fizz, Buzz and FizzBuzz for multiples of 3, 5 and both
for number in {1..100}
do
  if (( number % 15 == 0 ))
  then
    echo "FizzBuzz"
  elif (( number % 3 == 0 ))
  then
    echo "Fizz"
  elif (( number % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$number"
  fi
done
