#!/usr/bin/env bash
# This script is displaying the username, user id and home directory path of the users in /etc/passwd
while IFS= read -r line
do
  echo "$line" | cut -d ':' -f 1,3,6
done < /etc/passwd
