#!/usr/bin/env bash
# This script is looping from 1 to 10 and displaying bad luck on the 4th, good luck on the 8th, Best School on the others
count=1
while [ "$count" -le 10 ]
do
  if [ "$count" -eq 4 ]
  then
    echo "bad luck"
  elif [ "$count" -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((count++))
done
