#!/usr/bin/env bash
# This script is creating a PID file and reacting to the SIGTERM, SIGINT and SIGQUIT signals
pidfile="/var/run/myscript.pid"

on_sigterm() {
  echo "I hate the kill command"
  rm -f "$pidfile"
  exit
}

on_sigint() {
  echo "Y U no love me?!"
}

on_sigquit() {
  rm -f "$pidfile"
  exit
}

echo "$$" > "$pidfile"
trap on_sigterm SIGTERM
trap on_sigint SIGINT
trap on_sigquit SIGQUIT

while true
do
  echo "To infinity and beyond"
  sleep 2
done
